name: Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Ensure this matches your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack project
      run: dotnet pack --configuration Release --output ./output /p:NuspecFile=MyWebApi.nuspec

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_PACKAGE_TOKEN }}
      run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source https://nuget.pkg.github.com/sujitmeshramnashtech/index.json
